name: Sanity Check
on:
  push:
    branches:
      - master

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Codecrafters CLI
        run: |
          curl https://codecrafters.io/install.sh | sh
      - name: Add Codecrafters git remote
        run: |
          git config --global user.email "hello@silverhairs.engineer"
          git config --global user.name "silverhairs"
          git remote rm origin
          git remote add origin ${{secrets.REMOTE}}
          cat .git/config
      - name: Test
        run: |
          codecrafters test
