name: Sanity Check
on:
  push:
    branches:
      - master
jobs:
  codecrafters-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Codecrafters Test
        uses: silverhairs/codecrafters-test@v1
        with:
          remote-url: ${{ secrets.REMOTE }}
